# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e747771e3ddc583e383f7b1f462caacb9457508355201c29a81f2aa7ffa091619a546d10ac6ecf2123bdee71ae9e19d8ae41936670abadd79f0f6ab644ebfd9a

test:
  secret_key_base: dbe93959ea8fafd25357c07194cd4ee6b45c476fec5b245a6648e984ba071aca8dd7ac4f9c59d58b85332761040d79133359dae4ce4857dc0ecfe3cc9ad5bc2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
